apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
data:
  MONGO_URI: "mongodb://root:lakwet123@mongodb-service:27017/muchtodo?authSource=admin"
  DB_NAME: muchtodo
  PORT: "8080"
  JWT_EXPIRATION_HOURS: "72"